language: go
go:
- 1.11.x
go_import_path: github.com/annymsMthd/gogitver
script:
- env GO111MODULE=on make build
deploy:
  provider: releases
  api_key:
    secure: hH15qJcgRzaxpqunFM2appy6pYeQ5Hq3pRiAppFkRF7EnBg/ErL7TvNq+JVKQubTXlx6ojBLdKK/vbz8Jk3tdwtSO1tIPgDRGgdxeOyMLFisUiJ6ZwEnXhPctnhXjyZwsoYDAQQhAJyoBmrz6nNFqEoVMus10cr9Q8xd67XlXmeXz5HuDErypkJQxCQY1gUrspGFPNnZShg6TjaSRbzhauURPht9mfNGDW9pOCluBD0CWYCMbJkLxJtAAzxinQMGFstN/1oF7yRAwrnF2piNpvQXBj0Jnov4EQ3u7CbYYThItdIQIw/q6lgkmYD9MF3n4UCTNwCnxOOX81li9IYfQlqRmX8HJTP0BglL2prttYc41lxcwKhml5NNa0eRigmJXTzd8qyVftUREGfI950u14YgqzQALlZaXULrRhA3N8R5K1eAsniCraa6m9Bje515V+k4H/u4QPiRyTHSirE/u4kDPQ+CLySLRkX6HjSS0v87MeACgDxKUfPmxxbnLUSe6qNSN+WKH7JcZ/ORqV7L0prrzMttjkZnaaUmKDCV/CleYoBATMSp6hSX2fsyldWZ3HSdfyFSTTouG3fQgLYLikt2tH5JvC7Z2GQmF7F0KhtegDNOzroFyrrFEhL8d79IBqGBapvIza9NxEFdOh1JwhCniemXK1fRGTZl8+EHArw=
  file_glob: true
  skip_cleanup: true
  file: artifacts/*
  on:
    repo: annymsMthd/gogitver
    tags: true
